server:
  port : 8080


spring:
  datasource:
    username: root
    password: rootadmin
    url: jdbc:mysql://localhost:3306/fly?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver  运行的时候会提示这个没必要，所以这里注释掉了


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.fly.bean


#logging:
#  level:
#    com:
#      example:
#        mapper: debug